global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "nba-collector"
    static_configs:
      - targets: ["app:8000"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
